// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB798PzOJ0C4rJAYS4y-cV0n8LqogKd-tY',
    appId: '1:493543130357:web:2d68018f0ecb0fcbeb31bc',
    messagingSenderId: '493543130357',
    projectId: 'evaluation-note',
    authDomain: 'evaluation-note.firebaseapp.com',
    databaseURL: 'https://evaluation-note-default-rtdb.firebaseio.com',
    storageBucket: 'evaluation-note.firebasestorage.app',
    measurementId: 'G-PP20F27WE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASDmjD4QtsLWq_55JMw4WRP18ERctSfig',
    appId: '1:493543130357:android:e331b4690ba08e25eb31bc',
    messagingSenderId: '493543130357',
    projectId: 'evaluation-note',
    databaseURL: 'https://evaluation-note-default-rtdb.firebaseio.com',
    storageBucket: 'evaluation-note.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-EueI5C-lQTICJ-Dd2QPEDDhcOrX-y8o',
    appId: '1:493543130357:ios:39cbb9661fe864dceb31bc',
    messagingSenderId: '493543130357',
    projectId: 'evaluation-note',
    databaseURL: 'https://evaluation-note-default-rtdb.firebaseio.com',
    storageBucket: 'evaluation-note.firebasestorage.app',
    iosBundleId: 'com.trust.evolution',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-EueI5C-lQTICJ-Dd2QPEDDhcOrX-y8o',
    appId: '1:493543130357:ios:8ddaf99b1ea126e1eb31bc',
    messagingSenderId: '493543130357',
    projectId: 'evaluation-note',
    databaseURL: 'https://evaluation-note-default-rtdb.firebaseio.com',
    storageBucket: 'evaluation-note.firebasestorage.app',
    iosBundleId: 'ccom.trust.evolution',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB798PzOJ0C4rJAYS4y-cV0n8LqogKd-tY',
    appId: '1:493543130357:web:1826210c1ad602e5eb31bc',
    messagingSenderId: '493543130357',
    projectId: 'evaluation-note',
    authDomain: 'evaluation-note.firebaseapp.com',
    databaseURL: 'https://evaluation-note-default-rtdb.firebaseio.com',
    storageBucket: 'evaluation-note.firebasestorage.app',
    measurementId: 'G-WE4EVGFWLY',
  );
}
